version: '3'

services:

  app:
    container_name: app
    image: italog09/node
    # entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    networks:
      - node_network
    volumes:
      - .:/usr/src/app
    tty: true
    ports:
      - "3000:3000"
  
  nginx:
    image: italog09/nginx
    container_name: nginx
    networks:
      - node_network
    ports: 
      - "8080:80"

  # db:
  #   image: mysql:5.7
  #   command: --innodb-use-native-aio=0
  #   container_name: db
  #   restart: always
  #   tty: true
  #   volumes:
  #     - ./mysql:/var/lib/mysql
  #   environment:
  #     - MYSQL_DATABASE=nodedb
  #     - MYSQL_ROOT_PASSWORD=root
  #   networks:
  #     - node-network

networks:
  node_network:
    driver: bridge